export const metadata = {
  title: 'Routing',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'skyblue', padding: '30px' }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: 'gray', padding: '30px' }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
